version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/etl-api-new
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root 
  AfterInstall:
    - location: scripts/install_script.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
